apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    editable: true

  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    uid: opensearch
    editable: true
    jsonData:
      database: "otel-logs-*"
      version: "2.15.0"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
