http:
  routers:
    keycloak:
      rule: Host(`keycloak.tasso.local`)
      entryPoints:
        - websecure
      service: keycloak
      tls: {}

    vehicle-evaluation:
      rule: Host(`vehicle-evaluation.tasso.local`)
      entryPoints:
        - websecure
      service: vehicle-evaluation
      tls: {}

    commercial-api:
      rule: Host(`commercial.tasso.local`)
      entryPoints:
        - websecure
      service: commercial-api
      tls: {}

    gestauto-frontend:
      rule: Host(`gestauto.tasso.local`)
      entryPoints:
        - websecure
      service: gestauto-frontend
      tls: {}

  services:
    keycloak:
      loadBalancer:
        servers:
          - url: http://keycloak:8080

    vehicle-evaluation:
      loadBalancer:
        servers:
          - url: http://vehicle-evaluation:8081

    commercial-api:
      loadBalancer:
        servers:
          - url: http://commercial-api:8080

    gestauto-frontend:
      loadBalancer:
        servers:
          - url: http://gestauto-frontend:80

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/key.pem
